insert into users (name, user_name, email, address, phone, type, password) values ('Kipper', 'ktrimby0', 'kneem0@ask.com', '7757 Stoughton Drive', '1327528141', 'Male', 71564647);
insert into users (name, user_name, email, address, phone, type, password) values ('Ryann', 'rallmann1', 'rhalcro1@gnu.org', '41 Talmadge Junction', '5358549436', 'Female', 57513944);
insert into users (name, user_name, email, address, phone, type, password) values ('Ophelia', 'ocatto2', 'opaddemore2@dell.com', '13 Hoffman Lane', '8708684545', 'Female', 6841828);
insert into users (name, user_name, email, address, phone, type, password) values ('Charline', 'cganderton3', 'cbranchet3@newsvine.com', '81627 Maple Trail', '3859853608', 'Female', 31181489);
insert into users (name, user_name, email, address, phone, type, password) values ('Giorgio', 'ggildersleaves4', 'gminero4@yelp.com', '7312 Morrow Circle', '3744618585', 'Male', 93825857);
insert into users (name, user_name, email, address, phone, type, password) values ('Arden', 'akohen5', 'asondland5@bing.com', '51717 4th Trail', '1307743482', 'Female', 65209917);
insert into users (name, user_name, email, address, phone, type, password) values ('Antonius', 'aburds6', 'adundendale6@a8.net', '4 Brentwood Crossing', '1164581961', 'Male', 5281059);
insert into users (name, user_name, email, address, phone, type, password) values ('Lemar', 'ldeeman7', 'lrollinshaw7@businessinsider.com', '7598 Heffernan Terrace', '3986099868', 'Male', 45410146);
insert into users (name, user_name, email, address, phone, type, password) values ('Kevin', 'kcouvet8', 'kmursell8@china.com.cn', '4355 Talmadge Way', '5701831197', 'Male', 85475913);
insert into users (name, user_name, email, address, phone, type, password) values ('Verna', 'vmayler9', 'vphilbin9@nasa.gov', '8742 Tennyson Plaza', '3231688180', 'Female', 45655963);
insert into users (name, user_name, email, address, phone, type, password) values ('Kary', 'kdreighera', 'kcaplana@netlog.com', '3 Norway Maple Crossing', '4452793309', 'Female', 87826004);
insert into users (name, user_name, email, address, phone, type, password) values ('Nicholas', 'nmacfarlaneb', 'ngratrexb@fastcompany.com', '62218 Express Hill', '4657199277', 'Male', 96180190);
insert into users (name, user_name, email, address, phone, type, password) values ('Rhys', 'rpleagerc', 'rbroydc@google.nl', '206 Helena Drive', '5607776405', 'Male', 33070762);
insert into users (name, user_name, email, address, phone, type, password) values ('Marley', 'mjurischd', 'mhayd@princeton.edu', '3885 Wayridge Junction', '9971176340', 'Female', 19740568);
insert into users (name, user_name, email, address, phone, type, password) values ('Justen', 'jtowsee', 'jguyonnete@i2i.jp', '54937 Bluejay Lane', '2336156591', 'Male', 58426090);
insert into users (name, user_name, email, address, phone, type, password) values ('Ester', 'edockeryf', 'eleideckerf@bizjournals.com', '991 Little Fleur Road', '7851031945', 'Female', 6801391);
insert into users (name, user_name, email, address, phone, type, password) values ('Marylou', 'mestableg', 'mroswarng@w3.org', '3298 Browning Park', '8101664511', 'Female', 3780365);
insert into users (name, user_name, email, address, phone, type, password) values ('Eleanor', 'emaxstedh', 'emontierh@toplist.cz', '519 Crest Line Terrace', '9888560779', 'Female', 20758149);
insert into users (name, user_name, email, address, phone, type, password) values ('Eveleen', 'elovelandi', 'ehawicki@canalblog.com', '613 Bunker Hill Crossing', '8926247392', 'Female', 58727910);
insert into users (name, user_name, email, address, phone, type, password) values ('Wilt', 'wmessengerj', 'whedworthj@furl.net', '76185 Hollow Ridge Road', '8965032384', 'Male', 44124201);
insert into users (name, user_name, email, address, phone, type, password) values ('Deck', 'dkillockk', 'dsainerk@cyberchimps.com', '02689 Union Trail', '1233994156', 'Male', 48598085);
insert into users (name, user_name, email, address, phone, type, password) values ('Brena', 'bbraggerl', 'bdupreel@weibo.com', '714 Pine View Lane', '1162734963', 'Female', 89586006);
insert into users (name, user_name, email, address, phone, type, password) values ('Lela', 'lboardsm', 'lpalferym@edublogs.org', '8 Manley Avenue', '1336875742', 'Female', 20485003);
insert into users (name, user_name, email, address, phone, type, password) values ('Gabby', 'gsibleyn', 'grodbournen@merriam-webster.com', '323 Erie Court', '2652983021', 'Male', 9610269);
insert into users (name, user_name, email, address, phone, type, password) values ('Tedie', 'tbrundretto', 'tlaleveeo@theatlantic.com', '1926 Declaration Terrace', '4271130639', 'Male', 86020268);
insert into users (name, user_name, email, address, phone, type, password) values ('Rianon', 'rbaldryp', 'rhonnicottp@shareasale.com', '64 Birchwood Circle', '4629204501', 'Female', 9901561);
insert into users (name, user_name, email, address, phone, type, password) values ('Ezri', 'eharefootq', 'ebiaggelliq@apple.com', '6 Cottonwood Way', '6855937111', 'Male', 36085867);
insert into users (name, user_name, email, address, phone, type, password) values ('Gail', 'gcraykr', 'gkeitleyr@google.fr', '33653 Moland Alley', '4913246261', 'Female', 47066274);
insert into users (name, user_name, email, address, phone, type, password) values ('Farra', 'fodegaards', 'frollinshaws@tumblr.com', '18 Glendale Lane', '7008740713', 'Genderfluid', 16714426);
insert into users (name, user_name, email, address, phone, type, password) values ('Gladi', 'gdelucat', 'gsigwardt@networksolutions.com', '82665 Riverside Street', '8911256636', 'Female', 55576366);
insert into users (name, user_name, email, address, phone, type, password) values ('Janos', 'jkingmanu', 'jtuftinu@usa.gov', '2290 Declaration Park', '8196164158', 'Male', 62161339);
insert into users (name, user_name, email, address, phone, type, password) values ('Emlynn', 'ecapozziv', 'egoozeev@wired.com', '625 Delaware Hill', '1597022595', 'Female', 70175482);
insert into users (name, user_name, email, address, phone, type, password) values ('Carlyn', 'cmacuraw', 'cnaultyw@posterous.com', '3 Crescent Oaks Way', '6517921824', 'Female', 97137987);
insert into users (name, user_name, email, address, phone, type, password) values ('Brittne', 'borrowx', 'bjandourekx@google.pl', '23741 Warner Avenue', '9639229406', 'Female', 19154086);
insert into users (name, user_name, email, address, phone, type, password) values ('Jemimah', 'jjadosy', 'jdeddumy@exblog.jp', '319 Browning Point', '9769026211', 'Female', 35315513);
insert into users (name, user_name, email, address, phone, type, password) values ('Carr', 'cgriggz', 'calishonerz@google.com', '01441 Northview Pass', '4516159098', 'Male', 28721512);
insert into users (name, user_name, email, address, phone, type, password) values ('Gretel', 'gokeshott10', 'gpettigrew10@slideshare.net', '1 Londonderry Alley', '5552844343', 'Female', 26150408);
insert into users (name, user_name, email, address, phone, type, password) values ('Morgen', 'mtoxell11', 'mlearmond11@apple.com', '70 Arkansas Crossing', '7364901966', 'Female', 62231846);
insert into users (name, user_name, email, address, phone, type, password) values ('Izak', 'imaginot12', 'idanton12@alexa.com', '00204 Welch Park', '1785125486', 'Male', 16698585);
insert into users (name, user_name, email, address, phone, type, password) values ('Natala', 'nflahive13', 'nbuckberry13@csmonitor.com', '57 Vahlen Court', '3168266963', 'Female', 29960715);
insert into users (name, user_name, email, address, phone, type, password) values ('Tyne', 'tstaff14', 'tdoyley14@amazon.co.uk', '2930 Starling Pass', '4556605419', 'Female', 43068765);
insert into users (name, user_name, email, address, phone, type, password) values ('Merrel', 'mcoil15', 'mdobell15@opensource.org', '7 Nancy Alley', '7338771120', 'Male', 52404616);
insert into users (name, user_name, email, address, phone, type, password) values ('Deloria', 'dgaukroger16', 'dlillgard16@zdnet.com', '150 Southridge Crossing', '8893600735', 'Female', 19702494);
insert into users (name, user_name, email, address, phone, type, password) values ('Addie', 'afleg17', 'abiernat17@facebook.com', '980 Manley Drive', '4357262329', 'Female', 41154059);
insert into users (name, user_name, email, address, phone, type, password) values ('Itch', 'iyoslowitz18', 'iridler18@wikispaces.com', '79 Warbler Trail', '5169011550', 'Male', 33848383);
insert into users (name, user_name, email, address, phone, type, password) values ('Ardith', 'aabela19', 'amelhuish19@icq.com', '350 Vahlen Street', '5826950695', 'Female', 63781875);
insert into users (name, user_name, email, address, phone, type, password) values ('Joelie', 'jportress1a', 'jedwinson1a@thetimes.co.uk', '740 Morrow Plaza', '3024604990', 'Female', 24688611);
insert into users (name, user_name, email, address, phone, type, password) values ('Jessalin', 'jkilbride1b', 'jgregson1b@hp.com', '152 International Lane', '4845359746', 'Female', 61718369);
insert into users (name, user_name, email, address, phone, type, password) values ('Simeon', 'solkowicz1c', 'slapides1c@census.gov', '6 Loomis Parkway', '2141472068', 'Male', 2740040);
insert into users (name, user_name, email, address, phone, type, password) values ('Celesta', 'closemann1d', 'cdefraine1d@soup.io', '98 Packers Plaza', '8474511633', 'Female', 81914897);
//products
insert into products (name, description, image, price, quantity, user_id) values ('verapamil hydrochloride', 'Destruction of Left Orbit, Percutaneous Endoscopic Approach', 'http://dummyimage.com/246x100.png/dddddd/000000', 32.96, 3, 7);
insert into products (name, description, image, price, quantity, user_id) values ('Prednisone', 'Insertion of Infusion Device into L Buttock, Perc Approach', 'http://dummyimage.com/165x100.png/cc0000/ffffff', 94.57, 1, 4);
insert into products (name, description, image, price, quantity, user_id) values ('Carbamazepine', 'Release Left Cephalic Vein, Percutaneous Approach', 'http://dummyimage.com/162x100.png/dddddd/000000', 43.78, 1, 1);
insert into products (name, description, image, price, quantity, user_id) values ('Zinc Oxide', 'Insert of Infusion Dev into R Femoral Region, Perc Approach', 'http://dummyimage.com/188x100.png/ff4444/ffffff', 19.62, 1, 26);
insert into products (name, description, image, price, quantity, user_id) values ('panitumumab', 'Insert of Intralum Dev into L Com Iliac Art, Open Approach', 'http://dummyimage.com/245x100.png/ff4444/ffffff', 64.4, 1, 11);
insert into products (name, description, image, price, quantity, user_id) values ('OCTINOXATE and TITANIUM DIOXIDE', 'Reposition Abdominal Aorta, Percutaneous Endoscopic Approach', 'http://dummyimage.com/140x100.png/ff4444/ffffff', 32.55, 3, 39);
insert into products (name, description, image, price, quantity, user_id) values ('Chloroxylenol', 'Revision of Drainage Device in Lumsac Jt, Open Approach', 'http://dummyimage.com/108x100.png/cc0000/ffffff', 23.04, 2, 7);
insert into products (name, description, image, price, quantity, user_id) values ('Ibuprofen', 'Drainage of R Shoulder Bursa/Lig, Open Approach, Diagn', 'http://dummyimage.com/129x100.png/5fa2dd/ffffff', 44.81, 3, 21);
insert into products (name, description, image, price, quantity, user_id) values ('Stemphylium sarciniforms', 'Release Right Epididymis, Percutaneous Endoscopic Approach', 'http://dummyimage.com/166x100.png/ff4444/ffffff', 53.32, 2, 36);
insert into products (name, description, image, price, quantity, user_id) values ('insulin aspart', 'Excision of R Temporomandib Jt, Perc Endo Approach', 'http://dummyimage.com/228x100.png/ff4444/ffffff', 21.54, 2, 30);
insert into products (name, description, image, price, quantity, user_id) values ('OXYGEN', 'Drainage of Left Tunica Vaginalis, Perc Endo Approach', 'http://dummyimage.com/203x100.png/5fa2dd/ffffff', 54.2, 2, 40);
insert into products (name, description, image, price, quantity, user_id) values ('Hyoscyamine Sulfate', 'Reposition Right Fibula, Percutaneous Approach', 'http://dummyimage.com/215x100.png/ff4444/ffffff', 66.08, 1, 20);
insert into products (name, description, image, price, quantity, user_id) values ('Ethyl Alcohol', 'Release Left Knee Tendon, External Approach', 'http://dummyimage.com/244x100.png/cc0000/ffffff', 32.53, 3, 31);
insert into products (name, description, image, price, quantity, user_id) values ('POTASSIUM CHLORIDE', 'Resection of Pineal Body, Open Approach', 'http://dummyimage.com/250x100.png/dddddd/000000', 44.23, 1, 4);
insert into products (name, description, image, price, quantity, user_id) values ('Naproxen Sodium', 'Supplement Celiac Artery with Autol Sub, Open Approach', 'http://dummyimage.com/225x100.png/5fa2dd/ffffff', 56.08, 1, 5);
insert into products (name, description, image, price, quantity, user_id) values ('SALICYLIC ACID', 'Replacement of L Low Femur with Autol Sub, Open Approach', 'http://dummyimage.com/214x100.png/5fa2dd/ffffff', 34.7, 3, 7);
insert into products (name, description, image, price, quantity, user_id) values ('benzphetamine hydrochloride', 'Supplement R Int Carotid with Autol Sub, Perc Endo Approach', 'http://dummyimage.com/211x100.png/ff4444/ffffff', 51.54, 2, 16);
insert into products (name, description, image, price, quantity, user_id) values ('PSYLLIUM HUSK', 'Excision of Right Elbow Region, Percutaneous Approach', 'http://dummyimage.com/129x100.png/ff4444/ffffff', 29.85, 3, 4);
insert into products (name, description, image, price, quantity, user_id) values ('Clindamycin Phosphate', 'Plain Radiography of Whole Body', 'http://dummyimage.com/136x100.png/dddddd/000000', 59.0, 1, 48);
insert into products (name, description, image, price, quantity, user_id) values ('Zinc Oxide', 'Excision of Duodenum, Open Approach, Diagnostic', 'http://dummyimage.com/215x100.png/dddddd/000000', 27.2, 2, 46);
insert into products (name, description, image, price, quantity, user_id) values ('ISOPROPYL ALCOHOL', 'Bypass L Ext Iliac Art to B Int Ilia w Autol Vn, Perc Endo', 'http://dummyimage.com/227x100.png/cc0000/ffffff', 18.81, 3, 36);
insert into products (name, description, image, price, quantity, user_id) values ('Clopidogrel', 'Destruction of Para-aortic Body, Perc Endo Approach', 'http://dummyimage.com/191x100.png/cc0000/ffffff', 22.55, 3, 49);
insert into products (name, description, image, price, quantity, user_id) values ('diphenhydramine hydrochloride', 'Supplement L Metacarpocarp Jt w Synth Sub, Perc Endo', 'http://dummyimage.com/215x100.png/5fa2dd/ffffff', 47.25, 1, 49);
insert into products (name, description, image, price, quantity, user_id) values ('Actaea Spicata, Aesculus Hippocastanum,  into Eye, Via Opening', 'http://dummyimage.com/196x100.png/dddddd/000000', 38.33, 3, 49);
insert into products (name, description, image, price, quantity, user_id) values ('Triclosan', 'Occlusion of Left Lower Lobe Bronchus, Via Opening', 'http://dummyimage.com/188x100.png/cc0000/ffffff', 18.41, 2, 5);
insert into products (name, description, image, price, quantity, user_id) values ('AnticavityFluoride', 'Restrict of R Int Iliac Art with Intralum Dev, Open Approach', 'http://dummyimage.com/226x100.png/ff4444/ffffff', 77.49, 2, 16);
insert into products (name, description, image, price, quantity, user_id) values ('Galantamine Hydrobromide', 'Drainage of Left Parotid Gland, Open Approach', 'http://dummyimage.com/105x100.png/5fa2dd/ffffff', 79.08, 3, 23);
insert into products (name, description, image, price, quantity, user_id) values ('Eucalyptus Cuprum sulf.', 'Osteopathic Treatment of Sacrum using General Mobilization', 'http://dummyimage.com/240x100.png/cc0000/ffffff', 51.79, 3, 34);
insert into products (name, description, image, price, quantity, user_id) values ('SALICYLIC ACID', 'Fluoroscopy of Right Vertebral Artery using H Osm Contrast', 'http://dummyimage.com/243x100.png/ff4444/ffffff', 99.91, 2, 48);
insert into products (name, description, image, price, quantity, user_id) values ('ASPIRIN', 'Insertion of Intralum Dev into Low Art, Perc Endo Approach', 'http://dummyimage.com/150x100.png/5fa2dd/ffffff', 94.72, 1, 45);
insert into products (name, description, image, price, quantity, user_id) values ('Acetaminophen', 'Bypass Cereb Vent to Nasophar with Nonaut Sub, Open Approach', 'http://dummyimage.com/227x100.png/5fa2dd/ffffff', 68.44, 2, 26);
insert into products (name, description, image, price, quantity, user_id) values ('Diltiazem Hydrochloride', 'Remove of Autol Sub from R Thumb Phalanx, Perc Endo Approach', 'http://dummyimage.com/233x100.png/dddddd/000000', 97.24, 3, 30);
insert into products (name, description, image, price, quantity, user_id) values ('Avobenzone, Octinoxate, Octisalate, and Oxybenzone', 'Supplement Left Axillary Vein with Synth Sub, Open Approach', 'http://dummyimage.com/130x100.png/ff4444/ffffff', 42.26, 3, 22);
insert into products (name, description, image, price, quantity, user_id) values ('Acetaminophen', 'Repair Left Frontal Bone, Open Approach', 'http://dummyimage.com/103x100.png/cc0000/ffffff', 77.6, 2, 38);
insert into products (name, description, image, price, quantity, user_id) values ('Acetaminophen', 'Revision of Nonaut Sub in L Breast, Endo', 'http://dummyimage.com/182x100.png/cc0000/ffffff', 22.91, 3, 15);
insert into products (name, description, image, price, quantity, user_id) values ('influenza a virus','to R Femor A w Synth Sub, Open', 'http://dummyimage.com/105x100.png/cc0000/ffffff', 79.81, 3, 5);
insert into products (name, description, image, price, quantity, user_id) values ('Nabumetone', 'Removal of Int Fix from L Up Femur, Extern Approach', 'http://dummyimage.com/144x100.png/cc0000/ffffff', 75.87, 1, 39);
insert into products (name, description, image, price, quantity, user_id) values ('Acetaminophen', 'Release Vagina, Percutaneous Endoscopic Approach', 'http://dummyimage.com/176x100.png/cc0000/ffffff', 16.29, 3, 9);
insert into products (name, description, image, price, quantity, user_id) values ('oxycodone hydrochloride', 'Revision of Synthetic Substitute in Stomach, Via Opening', 'http://dummyimage.com/127x100.png/ff4444/ffffff', 19.9, 2, 28);
insert into products (name, description, image, price, quantity, user_id) values ('TITANIUM DIOXIDE', 'Insertion of Cardiac Lead into Coronary Vein, Perc Approach', 'http://dummyimage.com/227x100.png/dddddd/000000', 61.73, 1, 45);
insert into products (name, description, image, price, quantity, user_id) values ('galantamine hydrobromide', 'Excision of Upper Jaw, Percutaneous Endoscopic Approach', 'http://dummyimage.com/212x100.png/cc0000/ffffff', 28.98, 2, 17);
insert into products (name, description, image, price, quantity, user_id) values ('Coagulation Factor IX (Recombinant), Fc Fusion Protein', 'Replacement of L Brach Vein with Synth Sub, Open Approach', 'http://dummyimage.com/126x100.png/5fa2dd/ffffff', 98.58, 3, 35);
insert into products (name, description, image, price, quantity, user_id) values ('Coccus cacti, Drosera, Scilla maritima, Arsenicum iodatum, Causticum, Cuprum aceticum, Carbo vegetabilis, Kali Carbonicum, Lachesis mutus,', 'Removal of Monitoring Device from Lower Vein, Perc Approach', 'http://dummyimage.com/235x100.png/5fa2dd/ffffff', 33.86, 1, 17);
insert into products (name, description, image, price, quantity, user_id) values ('Diphenhydramine Hydrochloride', 'Revision of Monitoring Device in L Lung, Perc Endo Approach', 'http://dummyimage.com/194x100.png/dddddd/000000', 88.26, 1, 29);
insert into products (name, description, image, price, quantity, user_id) values ('AVOBENZONE, HOMOSALATE, OCTISALATE, OCTOCRYLENE, OXYBENZONE', 'Revision of Stimulator Lead in Ureter, Percutaneous Approach', 'http://dummyimage.com/229x100.png/ff4444/ffffff', 95.56, 1, 46);
insert into products (name, description, image, price, quantity, user_id) values ('populus deltoides subsp. monilifera pollen', 'Plain Radiography of Thoracic Aorta using Other Contrast', 'http://dummyimage.com/212x100.png/5fa2dd/ffffff', 74.62, 2, 13);
insert into products (name, description, image, price, quantity, user_id) values ('pomalidomide', 'Insert of Int Fix into R Acromioclav Jt, Perc Endo Approach', 'http://dummyimage.com/229x100.png/5fa2dd/ffffff', 89.57, 1, 41);
insert into products (name, description, image, price, quantity, user_id) values ('Captopril', 'New Technology, Bones, Reposition', 'http://dummyimage.com/163x100.png/dddddd/000000', 96.33, 1, 22);
insert into products (name, description, image, price, quantity, user_id) values ('valsartan', 'Destruction of R Foot Subcu/Fascia, Perc Approach', 'http://dummyimage.com/151x100.png/ff4444/ffffff', 48.74, 3, 22);
insert into products (name, description, image, price, quantity, user_id) values ('Ofloxacin', 'Excision of C-thor Jt, Perc Approach, Diagn', 'http://dummyimage.com/113x100.png/cc0000/ffffff', 77.38, 1, 29);
insert into products (name, description, image, price, quantity, user_id) values ('Doxycycline Hyclate', 'Inspection of Upper Vein, Percutaneous Approach', 'http://dummyimage.com/141x100.png/ff4444/ffffff', 54.5, 1, 15);
insert into products (name, description, image, price, quantity, user_id) values ('ANIDULAFUNGIN', 'Bypass L Com Iliac Art to R Int Ilia w Autol Art, Perc Endo', 'http://dummyimage.com/172x100.png/5fa2dd/ffffff', 40.13, 2, 37);
insert into products (name, description, image, price, quantity, user_id) values ('Diphenhydramine HCl', 'Removal of Nonaut Sub from Thor Disc, Open Approach', 'http://dummyimage.com/143x100.png/5fa2dd/ffffff', 95.81, 1, 45);
insert into products (name, description, image, price, quantity, user_id) values ('Fluoride', 'Insertion of Other Device into Left Buttock, Open Approach', 'http://dummyimage.com/245x100.png/ff4444/ffffff', 99.96, 1, 32);
insert into products (name, description, image, price, quantity, user_id) values ('SODIUM CHLORIDE', 'Revision of Autol Sub in Diaphragm, Perc Approach', 'http://dummyimage.com/159x100.png/ff4444/ffffff', 21.76, 3, 48);
insert into products (name, description, image, price, quantity, user_id) values ('ETHYL ALCOHOL', 'Excision of Left Tympanic Membrane, Open Approach', 'http://dummyimage.com/155x100.png/dddddd/000000', 17.34, 1, 37);
insert into products (name, description, image, price, quantity, user_id) values ('cyclobenzaprine hydrochloride', 'Release Right Tunica Vaginalis, Open Approach', 'http://dummyimage.com/214x100.png/cc0000/ffffff', 28.84, 1, 34);
insert into products (name, description, image, price, quantity, user_id) values ('Doxylamine Succinate', 'Removal of Infusion Device from Cranial Cav, Extern Approach', 'http://dummyimage.com/188x100.png/5fa2dd/ffffff', 85.48, 2, 28);
insert into products (name, description, image, price, quantity, user_id) values ('doxycycline hyclate', 'Revision of Synthetic Substitute in Stomach, Extern Approach', 'http://dummyimage.com/157x100.png/dddddd/000000', 29.91, 2, 45);
insert into products (name, description, image, price, quantity, user_id) values ('Menthol, Capsicum Annum Extract', 'Revision of Synthetic Substitute in R Hip Jt, Open Approach', 'http://dummyimage.com/181x100.png/dddddd/000000', 40.84, 1, 49);
insert into products (name, description, image, price, quantity, user_id) values ('Fexofenadine HCl', 'Occlusion of Bladder, Percutaneous Approach', 'http://dummyimage.com/107x100.png/5fa2dd/ffffff', 38.94, 1, 13);
insert into products (name, description, image, price, quantity, user_id) values ('Calcium Carbonate', 'Measurement of POC, Nervous Electr Activity, Endo', 'http://dummyimage.com/226x100.png/ff4444/ffffff', 15.94, 1, 26);
insert into products (name, description, image, price, quantity, user_id) values ('diphenhydramine hydrochloride', 'Replacement of L Abd Tendon with Nonaut Sub, Open Approach', 'http://dummyimage.com/171x100.png/5fa2dd/ffffff', 68.84, 2, 32);
insert into products (name, description, image, price, quantity, user_id) values ('OCTINOXATE, OXYBENZONE', 'Occlusion of R Subclav Art with Intralum Dev, Perc Approach', 'http://dummyimage.com/146x100.png/cc0000/ffffff', 37.61, 1, 19);
insert into products (name, description, image, price, quantity, user_id) values ('Pike', 'Supplement R Diaphragm with Synth Sub, Perc Endo Approach', 'http://dummyimage.com/225x100.png/cc0000/ffffff', 37.13, 3, 41);
insert into products (name, description, image, price, quantity, user_id) values ('olmesartan medoxomil and hydrochlorothiazide', 'Excision of Intracranial Vein, Percutaneous Approach', 'http://dummyimage.com/101x100.png/cc0000/ffffff', 95.91, 3, 47);
insert into products (name, description, image, price, quantity, user_id) values ('AVOBENZONE HOMOSALATE OCTISALATE OCTOCRYLENE OXYBENZONE', 'Inspection of Left Tympanic Membrane, Endo', 'http://dummyimage.com/221x100.png/ff4444/ffffff', 92.86, 2, 49);
insert into products (name, description, image, price, quantity, user_id) values ('Povidone-Iodine', 'Fusion L Metatarsotars Jt w Synth Sub, Perc Endo', 'http://dummyimage.com/194x100.png/ff4444/ffffff', 17.63, 2, 21);
insert into products (name, description, image, price, quantity, user_id) values ('PredniSONE', 'Removal of Infusion Device from L Wrist Jt, Perc Approach', 'http://dummyimage.com/217x100.png/dddddd/000000', 23.67, 3, 11);
insert into products (name, description, image, price, quantity, user_id) values ('Etodolac', 'Monitor Peripheral Nervous Electr Activity, Intraop, Extern', 'http://dummyimage.com/122x100.png/5fa2dd/ffffff', 96.78, 2, 12);
insert into products (name, description, image, price, quantity, user_id) values ('acetaminophen and codeine phosphate', 'Therapeutic Exercise Treatment of Resp Low Back/LE', 'http://dummyimage.com/189x100.png/5fa2dd/ffffff', 52.98, 3, 44);
insert into products (name, description, image, price, quantity, user_id) values ('Aspirin', 'Repair Right Submaxillary Gland, Percutaneous Approach', 'http://dummyimage.com/142x100.png/cc0000/ffffff', 54.67, 1, 40);
insert into products (name, description, image, price, quantity, user_id) values ('DEXTRAN, HYPROMELLOSE 2910', 'Alteration of L Elbow with Synth Sub, Perc Endo Approach', 'http://dummyimage.com/149x100.png/ff4444/ffffff', 90.85, 3, 12);
insert into products (name, description, image, price, quantity, user_id) values ('venlafaxine hydrochloride', 'Extirpation of Matter from Left Vas Deferens, Perc Approach', 'http://dummyimage.com/117x100.png/5fa2dd/ffffff', 98.89, 3, 48);
insert into products (name, description, image, price, quantity, user_id) values ('Nalbuphine Hydrochloride', 'Drainage of Left Shoulder Tendon, Perc Endo Approach, Diagn', 'http://dummyimage.com/139x100.png/ff4444/ffffff', 72.38, 1, 7);
insert into products (name, description, image, price, quantity, user_id) values ('Birch River Red', 'Revision of Reservoir in Trunk Subcu/Fascia, Extern Approach', 'http://dummyimage.com/130x100.png/ff4444/ffffff', 21.64, 3, 20);
insert into products (name, description, image, price, quantity, user_id) values ('ethyl alcohol', 'High Dose Rate (HDR) Brachytherapy of Liver using Cesium 137', 'http://dummyimage.com/159x100.png/cc0000/ffffff', 13.6, 3, 26);
insert into products (name, description, image, price, quantity, user_id) values ('TITANIUM DIOXIDE and OCTINOXATE', 'Dilate R Renal Art w 4+ Intralum Dev, Perc Endo', 'http://dummyimage.com/115x100.png/5fa2dd/ffffff', 71.59, 2, 29);
insert into products (name, description, image, price, quantity, user_id) values ('TOPIRAMATE', 'Repair Right Greater Saphenous Vein, Percutaneous Approach', 'http://dummyimage.com/237x100.png/cc0000/ffffff', 83.37, 3, 20);
insert into products (name, description, image, price, quantity, user_id) values ('pancrelipase', 'Dressing Techniques Treatment using Other Equipment', 'http://dummyimage.com/117x100.png/dddddd/000000', 18.97, 3, 36);
insert into products (name, description, image, price, quantity, user_id) values ('TRICLOSAN', 'Transfer Right Hip Tendon, Open Approach', 'http://dummyimage.com/225x100.png/cc0000/ffffff', 84.59, 3, 28);
insert into products (name, description, image, price, quantity, user_id) values ('bacitracin zinc, neomycin sulfate, polymyxin b sulfate', 'Repair Right Sublingual Gland, Percutaneous Approach', 'http://dummyimage.com/139x100.png/cc0000/ffffff', 66.18, 1, 27);
insert into products (name, description, image, price, quantity, user_id) values ('Dextromethorphan Hydrobromide, Guaifenesin, and Phenylephrine Hydrochloride', 'Removal of Nasal Packing Material', 'http://dummyimage.com/122x100.png/5fa2dd/ffffff', 98.23, 2, 41);
insert into products (name, description, image, price, quantity, user_id) values ('OATMEAL', 'Excision of Left Vocal Cord, Open Approach', 'http://dummyimage.com/175x100.png/dddddd/000000', 16.97, 3, 35);
insert into products (name, description, image, price, quantity, user_id) values ('Avobenzone, Homosalate, Octinoxate, Octisalate', 'Fluoroscopy of Right Humerus', 'http://dummyimage.com/195x100.png/ff4444/ffffff', 31.17, 1, 3);
insert into products (name, description, image, price, quantity, user_id) values ('OCINOXATE', 'Sensory/Processing Assessment of Integu Body', 'http://dummyimage.com/173x100.png/dddddd/000000', 30.01, 2, 40);
insert into products (name, description, image, price, quantity, user_id) values ('Medulla Arnica', 'CT Scan of Head & Neck using H Osm Contrast, Unenh, Enhance', 'http://dummyimage.com/111x100.png/cc0000/ffffff', 30.52, 2, 16);
insert into products (name, description, image, price, quantity, user_id) values ('Glyburide', 'Supplement Left Tarsal with Synth Sub, Perc Endo Approach', 'http://dummyimage.com/200x100.png/cc0000/ffffff', 48.27, 3, 18);
insert into products (name, description, image, price, quantity, user_id) values ('Duloxetine hydrochloride', 'Alteration of R Low Extrem with Nonaut Sub, Perc Approach', 'http://dummyimage.com/161x100.png/cc0000/ffffff', 46.43, 3, 18);
insert into products (name, description, image, price, quantity, user_id) values ('Amoxicillin', 'Supplement Glossophar Nrv with Autol Sub, Open Approach', 'http://dummyimage.com/124x100.png/cc0000/ffffff', 29.08, 2, 18);
insert into products (name, description, image, price, quantity, user_id) values ('SODIUM SULFACETAMIDE, SULFUR', 'Drainage of R Foot Bursa/Lig, Perc Endo Approach, Diagn', 'http://dummyimage.com/171x100.png/5fa2dd/ffffff', 22.8, 2, 26);
insert into products (name, description, image, price, quantity, user_id) values ('Neomycin sulfate, Polymyxin B Sulfate and Bacitracin Zinc', 'Insertion of Ext Fix into R Thumb Phalanx, Open Approach', 'http://dummyimage.com/181x100.png/ff4444/ffffff', 74.94, 3, 12);
insert into products (name, description, image, price, quantity, user_id) values ('Magnesium Chloride, Dextrose monohydrate, Lactic Acid, Sodium Chloride, Sodium Bicarbonate, and Potassium Chloride', 'Removal of Monitor Dev from Up Intest Tract, Open Approach', 'http://dummyimage.com/199x100.png/ff4444/ffffff', 94.38, 3, 8);
insert into products (name, description, image, price, quantity, user_id) values ('Barium Sulfate', 'Bypass L Com Iliac Vein to Low Vein w Autol Vn, Perc Endo', 'http://dummyimage.com/215x100.png/5fa2dd/ffffff', 90.25, 3, 50);
insert into products (name, description, image, price, quantity, user_id) values ('Sodium chloride', 'Drainage of Left Knee Joint with Drain Dev, Open Approach', 'http://dummyimage.com/190x100.png/5fa2dd/ffffff', 15.52, 2, 37);
insert into products (name, description, image, price, quantity, user_id) values ('Oxygen', 'Monitoring of Central Nervous Electr Activity, Perc Approach', 'http://dummyimage.com/241x100.png/ff4444/ffffff', 47.36, 3, 8);
insert into products (name, description, image, price, quantity, user_id) values ('salicylic acid', 'Replacement of L Renal Vein with Nonaut Sub, Open Approach', 'http://dummyimage.com/231x100.png/dddddd/000000', 82.99, 1, 28);
insert into products (name, description, image, price, quantity, user_id) values ('Loratadine', 'Excision of Right Upper Arm, Open Approach, Diagnostic', 'http://dummyimage.com/160x100.png/ff4444/ffffff', 63.83, 2, 3);
insert into products (name, description, image, price, quantity, user_id) values ('doxercalciferol', 'Revision of Autol Sub in Low Bursa/Lig, Extern Approach', 'http://dummyimage.com/122x100.png/cc0000/ffffff', 80.58, 3, 6);
insert into products (name, description, image, price, quantity, user_id) values ('Phenol', 'Repair Left Orbit, External Approach', 'http://dummyimage.com/112x100.png/5fa2dd/ffffff', 76.19, 2, 1);
//orders
insert into orders (number, createdAt, gotAt, total, user_id) values (173, '2023-02-27', '2022-12-13', 0.0, 38);
insert into orders (number, createdAt, gotAt, total, user_id) values (130, '2023-01-07', '2023-01-09', 0.0, 18);
insert into orders (number, createdAt, gotAt, total, user_id) values (130, '2023-01-02', '2022-12-09', 0.0, 5);
insert into orders (number, createdAt, gotAt, total, user_id) values (131, '2023-03-13', '2022-07-11', 0.0, 40);
insert into orders (number, createdAt, gotAt, total, user_id) values (143, '2022-07-30', '2022-10-19', 0.0, 13);
insert into orders (number, createdAt, gotAt, total, user_id) values (166, '2022-04-16', '2022-04-11', 0.0, 4);
insert into orders (number, createdAt, gotAt, total, user_id) values (173, '2022-04-05', '2023-02-23', 0.0, 43);
insert into orders (number, createdAt, gotAt, total, user_id) values (147, '2022-04-15', '2023-03-22', 0.0, 45);
insert into orders (number, createdAt, gotAt, total, user_id) values (162, '2022-04-26', '2022-05-07', 0.0, 46);
insert into orders (number, createdAt, gotAt, total, user_id) values (175, '2022-12-17', '2022-12-13', 0.0, 42);
insert into orders (number, createdAt, gotAt, total, user_id) values (173, '2023-03-15', '2022-06-23', 0.0, 9);
insert into orders (number, createdAt, gotAt, total, user_id) values (142, '2022-10-17', '2023-03-12', 0.0, 14);
insert into orders (number, createdAt, gotAt, total, user_id) values (162, '2023-01-06', '2022-04-21', 0.0, 21);
insert into orders (number, createdAt, gotAt, total, user_id) values (155, '2022-11-15', '2023-01-04', 0.0, 16);
insert into orders (number, createdAt, gotAt, total, user_id) values (132, '2022-11-04', '2022-05-06', 0.0, 40);
insert into orders (number, createdAt, gotAt, total, user_id) values (154, '2022-05-28', '2022-10-24', 0.0, 12);
insert into orders (number, createdAt, gotAt, total, user_id) values (137, '2022-08-16', '2023-03-01', 0.0, 12);
insert into orders (number, createdAt, gotAt, total, user_id) values (143, '2022-10-20', '2023-02-12', 0.0, 13);
insert into orders (number, createdAt, gotAt, total, user_id) values (163, '2022-06-24', '2022-08-11', 0.0, 34);
insert into orders (number, createdAt, gotAt, total, user_id) values (136, '2022-08-14', '2022-09-20', 0.0, 28);
insert into orders (number, createdAt, gotAt, total, user_id) values (132, '2022-04-28', '2022-11-19', 0.0, 10);
insert into orders (number, createdAt, gotAt, total, user_id) values (170, '2022-05-01', '2022-10-14', 0.0, 33);
insert into orders (number, createdAt, gotAt, total, user_id) values (126, '2022-10-15', '2022-04-04', 0.0, 38);
insert into orders (number, createdAt, gotAt, total, user_id) values (155, '2022-05-13', '2022-04-14', 0.0, 21);
insert into orders (number, createdAt, gotAt, total, user_id) values (169, '2022-08-18', '2022-12-04', 0.0, 41);
insert into orders (number, createdAt, gotAt, total, user_id) values (145, '2022-06-30', '2022-04-28', 0.0, 8);
insert into orders (number, createdAt, gotAt, total, user_id) values (127, '2022-05-27', '2022-08-28', 0.0, 18);
insert into orders (number, createdAt, gotAt, total, user_id) values (161, '2022-09-25', '2022-07-16', 0.0, 18);
insert into orders (number, createdAt, gotAt, total, user_id) values (162, '2023-03-08', '2022-06-06', 0.0, 35);
insert into orders (number, createdAt, gotAt, total, user_id) values (145, '2022-08-24', '2022-06-20', 0.0, 41);
insert into orders (number, createdAt, gotAt, total, user_id) values (161, '2022-11-22', '2022-08-30', 0.0, 12);
insert into orders (number, createdAt, gotAt, total, user_id) values (140, '2022-11-27', '2023-01-15', 0.0, 9);
insert into orders (number, createdAt, gotAt, total, user_id) values (151, '2023-02-20', '2023-02-20', 0.0, 10);
insert into orders (number, createdAt, gotAt, total, user_id) values (164, '2022-09-06', '2023-01-19', 0.0, 30);
insert into orders (number, createdAt, gotAt, total, user_id) values (138, '2022-07-30', '2022-06-02', 0.0, 10);
insert into orders (number, createdAt, gotAt, total, user_id) values (172, '2023-01-09', '2022-04-02', 0.0, 30);
insert into orders (number, createdAt, gotAt, total, user_id) values (162, '2022-09-01', '2022-06-03', 0.0, 6);
insert into orders (number, createdAt, gotAt, total, user_id) values (147, '2022-11-18', '2023-03-13', 0.0, 46);
insert into orders (number, createdAt, gotAt, total, user_id) values (170, '2023-03-11', '2023-02-26', 0.0, 22);
insert into orders (number, createdAt, gotAt, total, user_id) values (169, '2022-04-07', '2022-10-18', 0.0, 4);
insert into orders (number, createdAt, gotAt, total, user_id) values (174, '2022-09-24', '2022-11-28', 0.0, 38);
insert into orders (number, createdAt, gotAt, total, user_id) values (172, '2022-08-10', '2022-06-06', 0.0, 36);
insert into orders (number, createdAt, gotAt, total, user_id) values (171, '2022-08-20', '2022-05-01', 0.0, 32);
insert into orders (number, createdAt, gotAt, total, user_id) values (126, '2023-01-15', '2022-06-11', 0.0, 42);
insert into orders (number, createdAt, gotAt, total, user_id) values (150, '2022-07-23', '2023-03-09', 0.0, 47);
insert into orders (number, createdAt, gotAt, total, user_id) values (146, '2022-05-18', '2023-01-25', 0.0, 48);
insert into orders (number, createdAt, gotAt, total, user_id) values (125, '2022-04-07', '2022-07-17', 0.0, 7);
insert into orders (number, createdAt, gotAt, total, user_id) values (130, '2022-12-02', '2022-09-12', 0.0, 9);
insert into orders (number, createdAt, gotAt, total, user_id) values (151, '2022-04-10', '2022-04-17', 0.0, 19);
insert into orders (number, createdAt, gotAt, total, user_id) values (127, '2022-08-07', '2022-06-05', 0.0, 12);
//order_details
insert into order_details (name, quantity, price, total, product_id, order_id) values ('Menthol', 3, 29.68, 0.0, 2, 26);
insert into order_details (name, quantity, price, total, product_id, order_id) values ('Ensulizole, Octinoxate, and Oxybenzone', 3, 23.43, 0.0, 79, 49);
insert into order_details (name, quantity, price, total, product_id, order_id) values ('DIPHENHYDRAMINE HYDROCHLORIDE', 1, 47.03, 0.0, 8, 33);
insert into order_details (name, quantity, price, total, product_id, order_id) values ('doxazosin mesylate', 2, 30.31, 0.0, 90, 21);
insert into order_details (name, quantity, price, total, product_id, order_id) values ('AVOBENZONE, HOMOSALATE, OCTISALATE, OCTOCRYLENE', 2, 11.41, 0.0, 44, 32);
insert into order_details (name, quantity, price, total, product_id, order_id) values ('TOPIRAMATE', 3, 20.0, 0.0, 56, 27);
insert into order_details (name, quantity, price, total, product_id, order_id) values ('Octinoxate and Titanium dioxide', 2, 35.93, 0.0, 22, 5);
insert into order_details (name, quantity, price, total, product_id, order_id) values ('ceftazidime', 1, 24.83, 0.0, 16, 46);
insert into order_details (name, quantity, price, total, product_id, order_id) values ('Clindamycin in 5 Percent Dextrose', 3, 28.88, 0.0, 63, 14);
insert into order_details (name, quantity, price, total, product_id, order_id) values ('Threefold Balance', 3, 33.92, 0.0, 46, 4);
insert into order_details (name, quantity, price, total, product_id, order_id) values ('Losartan Potassium', 3, 24.73, 0.0, 63, 21);
insert into order_details (name, quantity, price, total, product_id, order_id) values ('FENTANYL', 3, 21.3, 0.0, 58, 12);
insert into order_details (name, quantity, price, total, product_id, order_id) values ('Diphenhydramine Hydrochloride', 3, 26.68, 0.0, 2, 24);
insert into order_details (name, quantity, price, total, product_id, order_id) values ('TOPIRAMATE', 2, 32.18, 0.0, 2, 37);
insert into order_details (name, quantity, price, total, product_id, order_id) values ('erythromycin', 1, 37.82, 0.0, 6, 33);
insert into order_details (name, quantity, price, total, product_id, order_id) values ('Prednisone', 1, 3.62, 0.0, 27, 7);
insert into order_details (name, quantity, price, total, product_id, order_id) values ('Aspen', 1, 43.88, 0.0, 90, 10);
insert into order_details (name, quantity, price, total, product_id, order_id) values ('benzethonium chloride and lidocaine', 1, 33.05, 0.0, 5, 48);
insert into order_details (name, quantity, price, total, product_id, order_id) values ('Sumatriptan', 1, 6.98, 0.0, 21, 12);
insert into order_details (name, quantity, price, total, product_id, order_id) values ('vanilla', 1, 48.0, 0.0, 66, 44);
insert into order_details (name, quantity, price, total, product_id, order_id) values ('Doxazosin', 2, 36.92, 0.0, 71, 1);
insert into order_details (name, quantity, price, total, product_id, order_id) values ('Naproxen Sodium', 1, 28.28, 0.0, 50, 48);
insert into order_details (name, quantity, price, total, product_id, order_id) values ('Hepatitis B Vaccine (Recombinant)', 3, 4.15, 0.0, 39, 10);
insert into order_details (name, quantity, price, total, product_id, order_id) values ('Hydralazine', 3, 45.24, 0.0, 57, 24);
insert into order_details (name, quantity, price, total, product_id, order_id) values ('Juglans regia, Myosotis arvensis, Scrophularia nodosa, Teucrium scroodonia, Veronica officinalis, Equisetum arvense, Fumaria officinalis, Geranium robertianum, Nasturtium aquaticum, Natrum sulphuricum', 1, 17.04, 0.0, 57, 22);
insert into order_details (name, quantity, price, total, product_id, order_id) values ('TITANIUM DIOXIDE', 1, 27.94, 0.0, 52, 16);
insert into order_details (name, quantity, price, total, product_id, order_id) values ('Adrenalinum, Tarentula cubensis, Aconitum nap., Arg. nit., Arsenicum alb., Baptisia, Chamomilla, Cypripedium, Digitalis, Gelsemium, Humulus, Ignatia, Impatiens glandulifera flos,', 2, 30.76, 0.0, 29, 45);
insert into order_details (name, quantity, price, total, product_id, order_id) values ('Diphenhydramine hydrochloride and Phenylephrine hydrochloride', 2, 29.0, 0.0, 9, 12);
insert into order_details (name, quantity, price, total, product_id, order_id) values ('Acetaminophen, Chlorpheniramine maleate, Dextromethorphan HBr, Phenylephrine HCl', 3, 14.52, 0.0, 40, 13);
insert into order_details (name, quantity, price, total, product_id, order_id) values ('Losartan Potassium', 2, 32.68, 0.0, 47, 41);
insert into order_details (name, quantity, price, total, product_id, order_id) values ('Yellow Pine', 2, 23.37, 0.0, 54, 3);
insert into order_details (name, quantity, price, total, product_id, order_id) values ('Menthol', 1, 14.25, 0.0, 16, 40);
insert into order_details (name, quantity, price, total, product_id, order_id) values ('Aconitum nap., Ambra, Anacardium orientale, Arg.nit., Asafoetida, Bryonia, Chamomilla, Cimicifuga, Coffea cruda, Cypripedium, Gelsemium', 1, 40.23, 0.0, 16, 13);
insert into order_details (name, quantity, price, total, product_id, order_id) values ('Treatment Set TS330171', 2, 19.99, 0.0, 3, 49);
insert into order_details (name, quantity, price, total, product_id, order_id) values ('LISINOPRIL', 3, 6.06, 0.0, 18, 37);
insert into order_details (name, quantity, price, total, product_id, order_id) values ('Naproxen', 2, 4.04, 0.0, 81, 40);
insert into order_details (name, quantity, price, total, product_id, order_id) values ('PYRITHIONE ZINC', 2, 49.2, 0.0, 57, 27);
insert into order_details (name, quantity, price, total, product_id, order_id) values ('Passiflora incarnata, Valeriana officinalis, Aurum metallicum, Bartya carbonica, Glonoinum, Phosphorus, Plumbum metallicum, Viscum album,', 3, 30.47, 0.0, 39, 12);
insert into order_details (name, quantity, price, total, product_id, order_id) values ('Acetaminophen, Dextromethorphan HBr, Doxylamine succinate, Phenylephrine HCl', 3, 27.95, 0.0, 61, 37);
insert into order_details (name, quantity, price, total, product_id, order_id) values ('Black Birch', 2, 38.05, 0.0, 98, 19);
insert into order_details (name, quantity, price, total, product_id, order_id) values ('GUAIFENESIN and PHENYLEPHRINE HYDROCHLORIDE', 2, 34.54, 0.0, 9, 2);
insert into order_details (name, quantity, price, total, product_id, order_id) values ('ETHYL ALCOHOL', 2, 12.13, 0.0, 83, 5);
insert into order_details (name, quantity, price, total, product_id, order_id) values ('haloperidol', 3, 33.89, 0.0, 41, 13);
insert into order_details (name, quantity, price, total, product_id, order_id) values ('Irbesartan and Hydrochlorothiazide', 3, 45.27, 0.0, 51, 14);
insert into order_details (name, quantity, price, total, product_id, order_id) values ('FERROUS FUMARATE, ASCORBIC ACID, FOLIC ACID, CYANOCOBALAMIN', 3, 27.18, 0.0, 74, 29);
insert into order_details (name, quantity, price, total, product_id, order_id) values ('mineral oil, petrolatum, phenylephrine HCl', 1, 40.52, 0.0, 88, 3);
insert into order_details (name, quantity, price, total, product_id, order_id) values ('Octinoxate and Oxybenzone', 3, 35.36, 0.0, 76, 27);
insert into order_details (name, quantity, price, total, product_id, order_id) values ('liothyronine sodium', 1, 17.74, 0.0, 26, 25);
insert into order_details (name, quantity, price, total, product_id, order_id) values ('Avobenzone, Homosalate, Octisalate, Octocrylene and Oxybenzone', 2, 4.72, 0.0, 6, 5);
insert into order_details (name, quantity, price, total, product_id, order_id) values ('Olive', 2, 31.83, 0.0, 32, 24);
insert into order_details (name, quantity, price, total, product_id, order_id) values ('Benzocaine', 2, 38.26, 0.0, 23, 28);
insert into order_details (name, quantity, price, total, product_id, order_id) values ('Triclosan', 1, 23.93, 0.0, 87, 44);
insert into order_details (name, quantity, price, total, product_id, order_id) values ('TRAMADOL HYDROCHLORIDE', 2, 20.86, 0.0, 55, 50);
insert into order_details (name, quantity, price, total, product_id, order_id) values ('Octinoxate ,Avobenzone', 3, 49.92, 0.0, 57, 37);
insert into order_details (name, quantity, price, total, product_id, order_id) values ('Diphenhydramine HCl', 3, 37.03, 0.0, 13, 24);
insert into order_details (name, quantity, price, total, product_id, order_id) values ('Ethyl Alcohol', 2, 48.96, 0.0, 62, 2);
insert into order_details (name, quantity, price, total, product_id, order_id) values ('spironolactone', 3, 27.79, 0.0, 53, 42);
insert into order_details (name, quantity, price, total, product_id, order_id) values ('Benzoyl Peroxide', 3, 7.04, 0.0, 55, 27);
insert into order_details (name, quantity, price, total, product_id, order_id) values ('Metoprolol Tartrate', 1, 33.55, 0.0, 85, 14);
insert into order_details (name, quantity, price, total, product_id, order_id) values ('Losartan Potassium', 3, 2.56, 0.0, 76, 11);
insert into order_details (name, quantity, price, total, product_id, order_id) values ('PYRITHIONE ZINC', 2, 44.2, 0.0, 20, 32);
insert into order_details (name, quantity, price, total, product_id, order_id) values ('Valacyclovir hydrochloride', 1, 13.08, 0.0, 10, 36);
insert into order_details (name, quantity, price, total, product_id, order_id) values ('everolimus', 2, 2.38, 0.0, 53, 36);
insert into order_details (name, quantity, price, total, product_id, order_id) values ('pioglitazone hydrochloride', 1, 20.11, 0.0, 78, 48);
insert into order_details (name, quantity, price, total, product_id, order_id) values ('DEXTROSE, SOYBEAN OIL, SODIUM ACETATE, POTASSIUM CHLORIDE, SODIUM GLYCEROPHOSPHATE, MAGNESIUM SULFATE HEPTAHYDRATE, CALCIUM CHLORIDE, and LYSINE HYDROCHLORIDE', 1, 37.38, 0.0, 69, 34);
insert into order_details (name, quantity, price, total, product_id, order_id) values ('ACREMONIUM STRICTUM', 1, 21.76, 0.0, 59, 3);
insert into order_details (name, quantity, price, total, product_id, order_id) values ('Clarithromycin', 2, 40.93, 0.0, 8, 2);
insert into order_details (name, quantity, price, total, product_id, order_id) values ('Phenol', 1, 46.67, 0.0, 83, 9);
insert into order_details (name, quantity, price, total, product_id, order_id) values ('Apis mellifica, Arsenicum album, Baptisia tinctoria, Borax Capsicum annuum, Dulcamara, Echinacea, Mercurius corrosivus, Nitricum acidum, Pyrogenium, Rhus toxicodendron, Sulphur iodatum, Thuja occ iden', 1, 21.18, 0.0, 34, 46);
insert into order_details (name, quantity, price, total, product_id, order_id) values ('Isopropyl Alcohol', 1, 35.21, 0.0, 1, 18);
insert into order_details (name, quantity, price, total, product_id, order_id) values ('cyanocobalamin', 3, 23.77, 0.0, 1, 5);
insert into order_details (name, quantity, price, total, product_id, order_id) values ('Elm American', 2, 37.86, 0.0, 24, 3);
insert into order_details (name, quantity, price, total, product_id, order_id) values ('ALCOHOL', 2, 4.15, 0.0, 31, 41);
insert into order_details (name, quantity, price, total, product_id, order_id) values ('ALCOHOL', 2, 30.07, 0.0, 37, 47);
insert into order_details (name, quantity, price, total, product_id, order_id) values ('Antipyrine and Benzocaine', 3, 5.81, 0.0, 65, 17);
insert into order_details (name, quantity, price, total, product_id, order_id) values ('Insulin human', 3, 30.55, 0.0, 17, 23);
insert into order_details (name, quantity, price, total, product_id, order_id) values ('fluconazole', 2, 21.49, 0.0, 78, 40);
insert into order_details (name, quantity, price, total, product_id, order_id) values ('Aluminum Zirconium Tetrachlorohydrex GLY', 2, 37.54, 0.0, 83, 29);
insert into order_details (name, quantity, price, total, product_id, order_id) values ('OCTINOXATE and TITANIUM DIOXIDE', 3, 32.73, 0.0, 16, 8);
insert into order_details (name, quantity, price, total, product_id, order_id) values ('Neomycin, Polymyxin B, Pramoxine Hcl', 2, 30.71, 0.0, 33, 40);
insert into order_details (name, quantity, price, total, product_id, order_id) values ('midazolam hydrochloride', 2, 13.04, 0.0, 22, 18);
insert into order_details (name, quantity, price, total, product_id, order_id) values ('Tramadol Hydrochloride', 3, 48.25, 0.0, 71, 36);
insert into order_details (name, quantity, price, total, product_id, order_id) values ('trimethobenzamide hydrochloride', 3, 23.5, 0.0, 58, 21);
insert into order_details (name, quantity, price, total, product_id, order_id) values ('Acetaminophen', 1, 29.23, 0.0, 86, 2);
insert into order_details (name, quantity, price, total, product_id, order_id) values ('Diclofenac Sodium', 2, 31.16, 0.0, 16, 7);
insert into order_details (name, quantity, price, total, product_id, order_id) values ('Amlodipine Besylate', 1, 36.81, 0.0, 83, 43);
insert into order_details (name, quantity, price, total, product_id, order_id) values ('Octinoxate, Octisalate, Octocrylene, Oxybenzone, and Titanium dioxide', 2, 29.23, 0.0, 5, 6);
insert into order_details (name, quantity, price, total, product_id, order_id) values ('SIMETHICONE', 3, 28.37, 0.0, 99, 49);
insert into order_details (name, quantity, price, total, product_id, order_id) values ('Alcohol', 2, 3.31, 0.0, 1, 17);
insert into order_details (name, quantity, price, total, product_id, order_id) values ('Triclosan', 3, 48.72, 0.0, 52, 25);
insert into order_details (name, quantity, price, total, product_id, order_id) values ('BACITRACIN ZINC, NEOMYCIN SULFATE, POLYMYXIN-B SULFATE', 2, 9.4, 0.0, 23, 20);
insert into order_details (name, quantity, price, total, product_id, order_id) values ('Delsym', 1, 30.28, 0.0, 59, 5);
insert into order_details (name, quantity, price, total, product_id, order_id) values ('Acetaminophen and Diphenhydramine Citrate', 2, 44.43, 0.0, 79, 8);
insert into order_details (name, quantity, price, total, product_id, order_id) values ('Avobenzone, Homosalate, Octisalate, Octocrylene and Oxybenzone', 2, 31.85, 0.0, 97, 48);
insert into order_details (name, quantity, price, total, product_id, order_id) values ('FLUORIDE TREATMENT', 1, 34.77, 0.0, 71, 20);
insert into order_details (name, quantity, price, total, product_id, order_id) values ('Piperonyl butoxide, Pyrethrum extract', 1, 14.6, 0.0, 84, 1);
insert into order_details (name, quantity, price, total, product_id, order_id) values ('diphenhydramine hydrochloride', 3, 5.18, 0.0, 83, 48);
insert into order_details (name, quantity, price, total, product_id, order_id) values ('CALCITRIOL', 2, 20.47, 0.0, 9, 19);
insert into order_details (name, quantity, price, total, product_id, order_id) values ('Oxygen', 3, 45.92, 0.0, 34, 26);
insert into order_details (name, quantity, price, total, product_id, order_id) values ('Amoxicillin', 3, 44.08, 0.0, 36, 27);